// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered boat recommendation tool.
 *
 * - boatRecommendation - A function that provides boat recommendations based on user's viewing history.
 * - BoatRecommendationInput - The input type for the boatRecommendation function.
 * - BoatRecommendationOutput - The return type for the boatRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const BoatRecommendationInputSchema = z.object({
  viewedBoatDescriptions: z
    .array(z.string())
    .describe("An array of descriptions of boats the user has viewed."),
});
export type BoatRecommendationInput = z.infer<typeof BoatRecommendationInputSchema>;

const BoatRecommendationOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe("A list of boat recommendations based on the user's viewing history."),
});
export type BoatRecommendationOutput = z.infer<typeof BoatRecommendationOutputSchema>;

export async function boatRecommendation(input: BoatRecommendationInput): Promise<BoatRecommendationOutput> {
  return boatRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'boatRecommendationPrompt',
  input: {schema: BoatRecommendationInputSchema},
  output: {schema: BoatRecommendationOutputSchema},
  prompt: `You are a boat expert. Given the descriptions of boats a user has viewed, recommend other boats they might like.

  Here are the descriptions of the boats the user has viewed:
  {{#each viewedBoatDescriptions}}
  - {{{this}}}
  {{/each}}

  Please provide a list of boat recommendations, each recommendation should be a concise description:
  `,
});

const boatRecommendationFlow = ai.defineFlow(
  {
    name: 'boatRecommendationFlow',
    inputSchema: BoatRecommendationInputSchema,
    outputSchema: BoatRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
